"""
Title:              PlotProbabilities.py
Created by:         Andrew T. Hannington
Use with:           RadTrans_*.f90
                        Created by: A. P. Whitworth et al.

Date Created:       18/04/2019

Usage Notes:
			Plots BlackBody (BB), ModifiedBB (MBB), DifferentialMBB (DMBB)
			against wavelengths in log log space

Known bugs: //


"""

#===============================================================================#
#-------------------------------------------------------------------------------#
#		PlotProbabilities.py                                                    #
#		Plots the emission probabilities as generated by RadTrans_MainCode.F90  #
#		Details of this program below.                                          #
#-------------------------------------------------------------------------------#
import matplotlib.pyplot as plt
from matplotlib.ticker import (MultipleLocator, AutoMinorLocator)
import numpy as np
import pandas as pd
import math
import datetime
import os
from astropy import units as u

#------------------------------------------------------------------------------#
#Files for data to be imported for plotting.                                   #
lambdaDataPath  = "WLData.csv"
#Black Body Data:
BBconstantsPath = "BBconstants.csv"
BBAnalyticPath  = "BBAnalytic.csv"
BBmcrtPath 		= "BBMCRT.csv"
#Modified Black Body data:
MBconstantsPath = "MBconstants.csv"
MBAnalyticPath  = "MBAnalytic.csv"
MBmcrtPath 		= "MBMCRT.csv"
#Differential Modified Black Body data:
DMconstantsPath = "DMconstants.csv"
DMAnalyticPath  = "DMAnalytic.csv"
DMmcrtPath 		= "DMMCRT.csv"


##

#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------#

print()
print("Loading in data!")


																				#Read in Wavelength Data into single columned Data Frame.					  #
																				# We have omitted any infered header(column title) and skipped any white space#
lambdaData 	 = pd.read_csv(lambdaDataPath, header=None, \
skipinitialspace =True)

###Load into Data frame, omit header for data, skip spaces,
###    and tranpose for ease of plotting
BBconstants  = pd.read_csv(BBconstantsPath,delimiter=" ")						#We read the constants data into a Pandas Data Frame                          #
																				#We read in the analytic and MCRT data,currently in format of one row per temp#
																				#  we omit headers again [this would just be indices], skip whitespace, and   #
																				#    set any Fortran90 +/-"Infinity" values to NaN.							  #
																				#      We transpose the data so each data set is in one temperature index col #
																				#        i.e. one column per temperature, labelled by temp number [0,1,2,3...]#
BBAnalytic	 = pd.read_csv(BBAnalyticPath,delimiter=" ",header=None, \
skipinitialspace =True, na_values=["-Infinity", "Infinity"]).T
BBMCRT		 = pd.read_csv(BBmcrtPath,delimiter=" ",header=None, \
skipinitialspace =True, na_values=["-Infinity", "Infinity"]).T

MBconstants  = pd.read_csv(MBconstantsPath,delimiter=" ")
MBAnalytic	 = pd.read_csv(MBAnalyticPath,delimiter=" ",header=None, \
skipinitialspace =True, na_values=["-Infinity", "Infinity"]).T
MBMCRT		 = pd.read_csv(MBmcrtPath,delimiter=" ",header=None, \
skipinitialspace =True, na_values=["-Infinity", "Infinity"]).T

DMconstants  = pd.read_csv(DMconstantsPath,delimiter=" ")
DMAnalytic	 = pd.read_csv(DMAnalyticPath,delimiter=" ",header=None, \
skipinitialspace =True, na_values=["-Infinity", "Infinity"]).T
DMMCRT		 = pd.read_csv(DMmcrtPath,delimiter=" ",header=None, \
skipinitialspace =True, na_values=["-Infinity", "Infinity"]).T


print("Data loading complete!")

print()
print("Manipulating data!")
###
###Cut off end NaN from Fortran Carriage Return Space
###
																				#Here we have used online resources to determine the method by which to omit  #
																				#  the last row of the data. In this instance, the last row is a NaN brought  #
																				#    about by the space at each carriage return from Fortran90. Without this  #
																				#     fix then there is +1 "entry", creating a mismatch in len with wavelength#
BBAnalytic.drop(BBAnalytic.tail(1).index,inplace=True)
BBMCRT.drop(BBMCRT.tail(1).index,inplace=True)
MBAnalytic.drop(MBAnalytic.tail(1).index,inplace=True)
MBMCRT.drop(MBMCRT.tail(1).index,inplace=True)
DMAnalytic.drop(DMAnalytic.tail(1).index,inplace=True)
DMMCRT.drop(DMMCRT.tail(1).index,inplace=True)


																				#---CURRENTLY OMITTED CODE---												  #
																				#This section updates each columns of each data data-frame with a float64     #
																				#  version of the data. It "coerces" any non-numeric values to NaNs.		  #
# ###Replace all values with float64 and "coerce" unrecognised into NaNs
# for cols in BBAnalytic.columns.values:
	# BBAnalytic[cols] = pd.to_numeric(BBAnalytic[cols], errors='coerce')
	# BBMCRT[cols] = pd.to_numeric(BBMCRT[cols], errors='coerce')
	# MBAnalytic[cols] = pd.to_numeric(MBAnalytic[cols], errors='coerce')
	# MBMCRT[cols] = pd.to_numeric(MBMCRT[cols], errors='coerce')
	# DMAnalytic[cols] = pd.to_numeric(DMAnalytic[cols], errors='coerce')
	# DMMCRT[cols] = pd.to_numeric(DMMCRT[cols], errors='coerce')

#-------------------------------------------------------------------------------#
																				# Debugging print statements...												  #
# print()
# print("***")
# print("Data Details (for debugging):")
# print()
# print()
# print("Wavelength:")
# print(lambdaData,np.shape(lambdaData))
# print()
# print("BB:")
# print("Constants:",BBconstants,np.shape(BBconstants),BBconstants.columns.values)
# print("Analytic:",BBAnalytic,np.shape(BBAnalytic),BBAnalytic.columns.values)
# print("MCRT:",BBMCRT,np.shape(BBMCRT),BBMCRT.columns.values)
# print()
# print("MB:")
# print("Constants:",MBconstants,np.shape(MBconstants),MBconstants.columns.values)
# print("Constants:",MBconstants,np.shape(MBconstants),MBconstants.columns.values)
# print("Analytic:",MBAnalytic,np.shape(MBAnalytic),MBAnalytic.columns.values)
# print("MCRT:",MBMCRT,np.shape(MBMCRT),MBMCRT.columns.values)
# print()
# print("DM(BB):")
# print("Constants:",DMconstants,np.shape(DMconstants),DMconstants.columns.values)
# print("Analytic:",DMAnalytic,np.shape(DMAnalytic),DMAnalytic.columns.values)
# print("MCRT:",DMMCRT,np.shape(DMMCRT),DMMCRT.columns.values)



#-------------------------------------------------------------------------------
																				#Here we find the "limiting ordinates" (max and min for each axis).These are  #
																				#  part of the constants file, but the max and min must reflect the max and   #
																				#    min of all temperatures being shown so as to not omit any data.          #
																				#      It should be noted that the max and min cut off the lower y-axis, where#
																				#       results start to become spurious, and there is no available MCRT data.#
BBxMin = np.min(BBconstants['xmin'])
BBxMax = np.max(BBconstants['xmax'])
BByMin = np.min(BBconstants['ymin'])
BByMax = np.max(BBconstants['ymax'])

MBxMin = np.min(MBconstants['xmin'])
MBxMax = np.max(MBconstants['xmax'])
MByMin = np.min(MBconstants['ymin'])
MByMax = np.max(MBconstants['ymax'])

DMxMin = np.min(DMconstants['xmin'])
DMxMax = np.max(DMconstants['xmax'])
DMyMin = np.min(DMconstants['ymin'])
DMyMax = np.max(DMconstants['ymax'])

print()
print("Beginning Plotting!")

																				#A fairly standard plotting section. Each plot is overlayed with the MCRT and #
																				#  analytic data from each temperature. Each curve is labelled appropriately  #
																				#    with temperature and data type (analytic vs MCRT) using f-strings.       #
																				#     Xlims and Ylims set from above and in Fortran90 code. Plots are then    #
																				#      titled, labelled, legend added, and saved.      #


fig, ax = plt.subplots()
for i in range(0, len(BBconstants['temp'])):
	ax.plot(lambdaData,BBAnalytic[i], label=\
	f"BB Analytic T={BBconstants['temp'][i]}K")
	ax.plot(lambdaData,BBMCRT[i],label=\
	f"BB MCRT T={BBconstants['temp'][i]}K")
ax.set_xlabel(r'$Log10(\lambda)$ [$\mu m$]')
ax.set_ylabel(r'$Log10(B_{\lambda}(T))$ [/]')
ax.set_title(r'$Log10$(Planck Function) against $Log10$(Wavelength)'+'\n'\
+ 'for given temperatures')
ax.set_xlim(BBxMin, BBxMax)
ax.set_ylim(BByMin, BByMax)
ax.grid(which="both")
ax.xaxis.set_minor_locator(AutoMinorLocator())
ax.yaxis.set_minor_locator(AutoMinorLocator())

fig.legend(bbox_to_anchor=(.85,.85), loc="upper right", borderaxespad=0.)
fig.savefig('Log10(BB)_mcrt-vs-analytic_vs_Log10(wavelength)' + '.png')

fig, ax= plt.subplots()
for i in range(0, len(MBconstants['temp'])):
	ax.plot(lambdaData,MBAnalytic[i],label=\
	f"MB Analytic T={BBconstants['temp'][i]}K")
	ax.plot(lambdaData,MBMCRT[i],label=\
	f"MB MCRT T={MBconstants['temp'][i]}K")
ax.set_xlabel(r'$Log10(\lambda)$ [$\mu m$]')
ax.set_ylabel(r'$Log10(B_{Mod.,\lambda}(T))$ [/]')
ax.set_title(r'$Log10$(Modified Planck Function) against $Log10$(Wavelength)'+'\n'\
+ 'for given temperatures')
ax.set_xlim(MBxMin, MBxMax)
ax.set_ylim(MByMin, MByMax)
ax.grid(which="both")
ax.xaxis.set_minor_locator(AutoMinorLocator())
ax.yaxis.set_minor_locator(AutoMinorLocator())

fig.legend(bbox_to_anchor=(.85,.85), loc="upper right", borderaxespad=0.)
fig.savefig('Log10(MB)_mcrt-vs-analytic_vs_Log10(wavelength)'+'.png')

fig, ax = plt.subplots()
for i in range(0, len(DMconstants['temp'])):
	ax.plot(lambdaData,DMAnalytic[i],label=\
	f"DM Analytic T={DMconstants['temp'][i]}K")
	ax.plot(lambdaData,DMMCRT[i], label=\
	f"DM MCRT T={DMconstants['temp'][i]}K")
ax.set_xlabel(r'$Log10(\lambda)$ [$\mu m$]')
ax.set_ylabel(r'$Log10(B_{Dif. Mod.,\lambda}(T))$ [/]')
ax.set_title(r'$Log10$(Differential Modified Planck Function) against $Log10$(Wavelength)'+'\n'\
+ 'for given temperatures')
ax.set_xlim(DMxMin, DMxMax)
ax.set_ylim(DMyMin, DMyMax)
ax.grid(which="both")
ax.xaxis.set_minor_locator(AutoMinorLocator())
ax.yaxis.set_minor_locator(AutoMinorLocator())

fig.legend(bbox_to_anchor=(.85,.85), loc="upper right", borderaxespad=0.)
fig.savefig('Log10(DMBB)_mcrt-vs-analytic_vs_Log10(wavelength)'+'.png')

finxMin = min([DMxMin, MBxMin])
finxMax = max([DMxMax, MBxMax])
finyMin = min([DMyMin, MByMin])
finyMax = max([DMyMax, MByMax])

fig,ax = plt.subplots()
for i in range(0, len(MBconstants['temp'])):
	ax.plot(lambdaData,DMAnalytic[i],label=\
	f"DM Analytic T={DMconstants['temp'][i]}K")
	ax.plot(lambdaData,MBAnalytic[i], label=\
	f"MB Analytic T={MBconstants['temp'][i]}K")
ax.set_xlabel(r'$Log10(\lambda)$ [$\mu m$]')
ax.set_ylabel(r'$Log10(B_{\lambda}(T))$ [/]')
ax.set_title(r'$Log10$(Modified Planck Function) against $Log10$(Wavelength)'+'\n'\
+ r'& $Log10$(Differential Modified Planck Function)'+'\n' \
+ r' against $Log10$(Wavelength)for given temperatures')
ax.set_xlim(DMxMin, DMxMax)
ax.set_ylim(DMyMin, DMyMax)
ax.grid(which="both")
ax.xaxis.set_minor_locator(AutoMinorLocator())
ax.yaxis.set_minor_locator(AutoMinorLocator())

fig.legend(bbox_to_anchor=(.85,.85), loc="upper right", borderaxespad=0.)
fig.savefig('Log10(MB)-analytic_Log10(DMBB)-analytic_vs_Log10(wavelength)' +'.png')

plt.show()

print()
print("END")																	#---PROGRAM END!---													 		  #
